# Generated by Django 4.2 on 2023-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(error_messages={'unique': 'Topping already exists'}, max_length=200, unique=True)),
            ],
        ),
    ]
