# Generated by Django 4.2 on 2023-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_created PizzaTopping model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatopping',
            name='topping_name',
            field=models.CharField(db_collation='NOCASE', error_messages={'unique': 'Topping already exists'}, max_length=200, unique=True),
        ),
    ]
