# Generated by Django 4.2 on 2023-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_alter_pizzatopping_topping_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzatopping',
            old_name='topping_name',
            new_name='topping',
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.CharField(db_collation='NOCASE', error_messages={'unique': 'Pizza already exists'}, max_length=200, unique=True)),
                ('toppings', models.ManyToManyField(to='pizza.pizzatopping')),
            ],
        ),
    ]
