# Generated by Django 4.2 on 2023-12-16 12:47

from django.db import migrations

# https://docs.djangoproject.com/en/4.2/ref/migration-operations/

def create_default_groups_and_users(apps, schema_editor):
    """
    Creates Pizza Owner and Pizza Chef
    Creates owner and chef user and assigns them to group
    """
    # Creates groups
    Group = apps.get_model('auth', 'Group')
    owner_group = Group.objects.create(name='Pizza Owner')
    chef_group = Group.objects.create(name='Pizza Chef')
    
    # Creates users
    User = apps.get_model('auth', 'User')
    owner_user = User.objects.create_user(username='owner', password='1234')
    chef_user = User.objects.create_user(username='chef', password='1234')
    admin_user = User.objects.create_user(username='admin', password='1234')

    # Makes admin superuser
    admin_user.is_staff=True
    admin_user.is_superuser=True
    admin_user.save()

    # Assigns users to groups
    owner_user.groups.add(owner_group)
    chef_user.groups.add(chef_group)

class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_rename_topping_name_pizzatopping_topping_pizza'),

    ]

    operations = [
        migrations.RunPython(create_default_groups_and_users)
    ]
