# Generated by Django 4.2 on 2023-12-16 13:42

from django.db import migrations
from django.contrib.auth.management import create_permissions

def assign_permissions(apps, schema_editor):
    """
    Assigns permission to Chef and Owner groups
    """
    # https://dandavies99.github.io/posts/2021/11/django-permissions/#goal-2-set-up-groups-when-the-project-is-initialised-using-a-data-migration
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    chef_group, created = Group.objects.get_or_create(name='Pizza Chef')
    owner_group, created = Group.objects.get_or_create(name='Pizza Owner')

    view_topping = Permission.objects.get(codename='view_pizzatopping')
    add_topping = Permission.objects.get(codename='add_pizzatopping')
    change_topping = Permission.objects.get(codename='change_pizzatopping')
    delete_topping = Permission.objects.get(codename='delete_pizzatopping')
    view_pizza = Permission.objects.get(codename='view_pizza')
    add_pizza = Permission.objects.get(codename='add_pizza')
    change_pizza = Permission.objects.get(codename='change_pizza')
    delete_pizza = Permission.objects.get(codename='delete_pizza')
    owner_group.permissions.add(add_topping, view_topping, change_topping, delete_topping)
    chef_group.permissions.add(view_pizza, add_pizza, change_pizza, delete_pizza)

class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_custom_migration_for_creating_groups_on_migration'),
    ]

    operations = [
        migrations.RunPython(assign_permissions)
    ]
